steps:
  compile:
    image: golang:1.8.5
    commands:
      - go build -o dist/startup

  docker:
    image: crun/docker
    registry_name: coderun
    repo_name: hellwen/startup
    dockerfile_content: |
        FROM alpine:3.4
        ADD dist/startup /bin/
        ENTRYPOINT ["/bin/startup"]
    context: .
    tags: latest

  deploy:
    image: crun/kube
    cluster_name: hssh1
    deploy_name: startup
