apiVersion: apps/v1
kind: Deployment
metadata:
  name: startup
spec:
  replicas: 1
  selector:
    matchLabels:
      app: startup
  template:
    metadata:
      labels:
        app: startup
    spec:
      containers:
      - name: startup
        image: dev.crun.top/trams/startup
